In [1]:
import numpy as np
import pandas as pd
from google.cloud import bigquery

pd.set_option('display.max_rows', None)

client = bigquery.Client()
project = client.project
datasets = ['bronze', 'silver', 'gold']

In [2]:
for ds in datasets:
    schema_query = f"""
        SELECT table_name, column_name
        FROM `{project}.{ds}.INFORMATION_SCHEMA.COLUMNS`
        WHERE table_name NOT LIKE '%_view%'
          AND data_type NOT LIKE 'ARRAY%'
          AND data_type NOT LIKE 'STRUCT%'
    """
    schema_df = client.query(schema_query).to_dataframe()

    df_dataset_results = pd.DataFrame()

    for table, group in schema_df.groupby('table_name'):
        cols = group['column_name'].tolist()
        null_counts = [f"COUNTIF(`{col}` IS NULL) AS `{col}`" for col in cols]

        q = f"""
        SELECT '{table}' AS table_name, COUNT(*) AS row_count,
        {', '.join(null_counts)}
        FROM `{project}.{ds}.{table}`
        """

        try:
            df_res = client.query(q).to_dataframe()
            df_melted = df_res.melt(id_vars=['table_name', 'row_count'], var_name='column_name', value_name='null_count')
            df_dataset_results = pd.concat([df_dataset_results, df_melted], ignore_index=True)
        except Exception as e:
            pass

    if not df_dataset_results.empty:
        df_dataset_results['null_percentage'] = np.where(
            df_dataset_results['row_count'] == 0,
            0.0,
            (df_dataset_results['null_count'] / df_dataset_results['row_count']) * 100
        )
        df_dataset_results['null_percentage'] = df_dataset_results['null_percentage'].round(2)

        df_dataset_results = df_dataset_results.sort_values(
            by=['null_percentage', 'null_count'],
            ascending=[False, False]
        ).reset_index(drop=True)

        print(f"NULL DATA REPORT - LAYER: {ds.upper()}")

        display(df_dataset_results)
    else:
        print(f"\nNo data to analyze in layer {ds}")

NULL DATA REPORT - LAYER: BRONZE

,table_name,row_count,column_name,null_count,null_percentage
0,raw_planner_BakeryOrders,5743,PlatformDiscountId,5743,100.00
1,raw_wallet_PaymentMethods,187,CardBrand,187,100.00
2,raw_wallet_RefundCreationErrors,122,StatusCode,122,100.00
3,raw_wallet_RefundCreationErrors,122,CodeLiteral,122,100.00
4,raw_catalog_ProductAttribute,3,BakeryProductId,3,100.00
5,raw_customer_manager_Consents,3,ExpiryDate,3,100.00
6,raw_wallet_Payments,2235,Error,2234,99.96
7,raw_wallet_Refunds,1063,ClaimId,1059,99.62
8,raw_wallet_Payments,2235,DiscountedAmount,2168,97.00
9,raw_wallet_Payments,2235,DiscountId,2167,96.96
10,raw_wallet_Discounts,21,CustomerId,19,90.48
11,raw_delivery_manager_DeliveryItems,1741,PackedQuantity,1552,89.14
12,raw_catalog_BakeryOffer,145,NextVersionId,121,83.45
13,raw_delivery_account_manager_Address,6,Voivodeship,5,83.33
14,raw_delivery_account_manager_Address,6,District,5,83.33
15,raw_delivery_account_manager_Address,6,PostOffice,5,83.33
16,raw_wallet_Discounts,21,DiscountFlatRate,16,76.19
17,raw_wallet_Payments,2235,ClientId,1681,75.21
18,raw_wallet_Refunds,1063,BaseAmount,767,72.15
19,raw_catalog_BakeryOffer,145,PreviousVersionOfferId,78,53.79
20,raw_claim_manager_ClaimItems,46,PictureName,24,52.17
21,raw_client_manager_Client,4,FullFormalName,2,50.00
22,raw_client_manager_Client,4,Story,2,50.00
23,raw_delivery_account_manager_BankAccount,2,BankName,1,50.00
24,raw_catalog_BakeryProduct,83,PreviousVersionProductId,41,49.40
25,raw_catalog_BakeryProduct,83,ModifiedVersionProductId,41,49.40
26,raw_wallet_Discounts,21,ClientId,10,47.62
27,raw_wallet_PaymentMethods,187,MarkedAsPrimaryOnCreation,83,44.39
28,raw_wallet_Payments,2235,DeliveryId,974,43.58
29,raw_catalog_OfferProduct,151,PictureFieName,60,39.74
30,raw_customer_manager_Customer,176,Name,55,31.25
31,raw_wallet_Discounts,21,LinkToTerms,6,28.57
32,raw_client_manager_Client,4,NIP,1,25.00
33,raw_wallet_Discounts,21,DiscountPercentage,5,23.81
34,raw_customer_manager_CustomerAddress,544,AddressName,115,21.14
35,raw_customer_manager_CustomerAddress,544,Address,70,12.87
36,raw_delivery_manager_DeliveryManArea,578,DeliveryManId,53,9.17
37,raw_claim_manager_ClaimItems,46,Description,4,8.70
38,raw_delivery_manager_Deliveries,1162,DeliveryManId,84,7.23
39,raw_planner_BakeryOrderItems,9454,PlannerItemId,392,4.15
40,raw_delivery_manager_Deliveries,1162,AddressName,34,2.93
41,raw_delivery_manager_DeliveryItems,1741,PictureFileName,49,2.81
42,raw_catalog_Allergen,15,Id,0,0.00
43,raw_catalog_Allergen,15,Name,0,0.00
44,raw_catalog_Allergen,15,IsUsed,0,0.00
45,raw_catalog_Allergen,15,Created,0,0.00
46,raw_catalog_Allergen,15,Updated,0,0.00
47,raw_catalog_Allergen,15,UserId,0,0.00
48,raw_catalog_Availability,144,Id,0,0.00
49,raw_catalog_Availability,144,Monday,0,0.00
50,raw_catalog_Availability,144,Tuesday,0,0.00
51,raw_catalog_Availability,144,Wednesday,0,0.00
52,raw_catalog_Availability,144,Thursday,0,0.00
53,raw_catalog_Availability,144,Friday,0,0.00
54,raw_catalog_Availability,144,Saturday,0,0.00
55,raw_catalog_Availability,144,Sunday,0,0.00
56,raw_catalog_Availability,144,AvailableDateFrom,0,0.00
57,raw_catalog_Availability,144,AvailableDateTo,0,0.00
58,raw_catalog_Availability,144,Created,0,0.00
59,raw_catalog_Availability,144,Updated,0,0.00
60,raw_catalog_Availability,144,UserId,0,0.00
61,raw_catalog_BakeryOffer,145,Id,0,0.00
62,raw_catalog_BakeryOffer,145,Name,0,0.00
63,raw_catalog_BakeryOffer,145,Price,0,0.00
64,raw_catalog_BakeryOffer,145,State,0,0.00
65,raw_catalog_BakeryOffer,145,Type,0,0.00
66,raw_catalog_BakeryOffer,145,AvailableStock,0,0.00
67,raw_catalog_BakeryOffer,145,IsAvailable,0,0.00
68,raw_catalog_BakeryOffer,145,PictureFileName,0,0.00
69,raw_catalog_BakeryOffer,145,PlatformClientId,0,0.00
70,raw_catalog_BakeryOffer,145,VatRateId,0,0.00
71,raw_catalog_BakeryOffer,145,VAT,0,0.00
72,raw_catalog_BakeryOffer,145,Created,0,0.00
73,raw_catalog_BakeryOffer,145,Updated,0,0.00
74,raw_catalog_BakeryOffer,145,UserId,0,0.00
75,raw_catalog_BakeryProduct,83,Id,0,0.00
76,raw_catalog_BakeryProduct,83,Name,0,0.00
77,raw_catalog_BakeryProduct,83,Description,0,0.00
78,raw_catalog_BakeryProduct,83,State,0,0.00
79,raw_catalog_BakeryProduct,83,PictureFileName,0,0.00
80,raw_catalog_BakeryProduct,83,BakeryProductsTypeId,0,0.00
81,raw_catalog_BakeryProduct,83,PlatformClientId,0,0.00
82,raw_catalog_BakeryProduct,83,Created,0,0.00
83,raw_catalog_BakeryProduct,83,Updated,0,0.00
84,raw_catalog_BakeryProduct,83,UserId,0,0.00
85,raw_catalog_BakeryProduct,83,Weight,0,0.00
86,raw_catalog_BakeryProductSiteNew,143,Id,0,0.00
87,raw_catalog_BakeryProductSiteNew,143,BakeryProductId,0,0.00
88,raw_catalog_BakeryProductSiteNew,143,SiteId,0,0.00
89,raw_catalog_BakeryProductSiteNew,143,Created,0,0.00
90,raw_catalog_BakeryProductSiteNew,143,Updated,0,0.00
91,raw_catalog_BakeryProductSiteNew,143,UserId,0,0.00
92,raw_catalog_BakeryProductsTypes,4,Id,0,0.00
93,raw_catalog_BakeryProductsTypes,4,Name,0,0.00
94,raw_catalog_BakeryProductsTypes,4,PictureFileName,0,0.00
95,raw_catalog_BakeryProductsTypes,4,Created,0,0.00
96,raw_catalog_BakeryProductsTypes,4,Updated,0,0.00
97,raw_catalog_BakeryProductsTypes,4,UserId,0,0.00
98,raw_catalog_BakeryProductsTypes,4,ProductTypeDisplayOrder,0,0.00
99,raw_catalog_Nutrition,83,Id,0,0.00
100,raw_catalog_Nutrition,83,Calories,0,0.00
101,raw_catalog_Nutrition,83,TotalFats,0,0.00
102,raw_catalog_Nutrition,83,SaturatedFats,0,0.00
103,raw_catalog_Nutrition,83,TotalCarbohydrates,0,0.00
104,raw_catalog_Nutrition,83,Sugar,0,0.00
105,raw_catalog_Nutrition,83,Protein,0,0.00
106,raw_catalog_Nutrition,83,Sodium,0,0.00
107,raw_catalog_Nutrition,83,Created,0,0.00
108,raw_catalog_Nutrition,83,Updated,0,0.00
109,raw_catalog_Nutrition,83,UserId,0,0.00
110,raw_catalog_Nutrition,83,ProductId,0,0.00
111,raw_catalog_OfferAvailability,144,Id,0,0.00
112,raw_catalog_OfferAvailability,144,BakeryOfferId,0,0.00
113,raw_catalog_OfferLocation,797,Id,0,0.00
114,raw_catalog_OfferLocation,797,LocationId,0,0.00
115,raw_catalog_OfferLocation,797,BakeryOfferId,0,0.00
116,raw_catalog_OfferLocation,797,Created,0,0.00
117,raw_catalog_OfferLocation,797,Updated,0,0.00
118,raw_catalog_OfferLocation,797,UserId,0,0.00
119,raw_catalog_OfferProduct,151,Id,0,0.00
120,raw_catalog_OfferProduct,151,ProductId,0,0.00
121,raw_catalog_OfferProduct,151,ProductPrice,0,0.00
122,raw_catalog_OfferProduct,151,ProductName,0,0.00
123,raw_catalog_OfferProduct,151,BakeryOfferId,0,0.00
124,raw_catalog_OfferProduct,151,ProductCount,0,0.00
125,raw_catalog_OfferProduct,151,IsAvailableInOffer,0,0.00
126,raw_catalog_OfferProduct,151,IsAvailableInOfferSite,0,0.00
127,raw_catalog_OfferProduct,151,ProductInOfferPrice,0,0.00
128,raw_catalog_OfferProduct,151,VATForProductInOffer,0,0.00
129,raw_catalog_OfferProduct,151,Created,0,0.00
130,raw_catalog_OfferProduct,151,Updated,0,0.00
131,raw_catalog_OfferProduct,151,UserId,0,0.00
132,raw_catalog_OfferSite,278,Id,0,0.00
133,raw_catalog_OfferSite,278,SiteId,0,0.00
134,raw_catalog_OfferSite,278,BakeryOfferId,0,0.00
135,raw_catalog_OfferSite,278,Created,0,0.00
136,raw_catalog_OfferSite,278,Updated,0,0.00
137,raw_catalog_OfferSite,278,UserId,0,0.00
138,raw_catalog_PrivateIngredient,3,Id,0,0.00
139,raw_catalog_PrivateIngredient,3,PlatformClientId,0,0.00
140,raw_catalog_PrivateIngredient,3,Name,0,0.00
141,raw_catalog_PrivateIngredient,3,Unit,0,0.00
142,raw_catalog_PrivateIngredient,3,Created,0,0.00
143,raw_catalog_PrivateIngredient,3,Updated,0,0.00
144,raw_catalog_PrivateIngredient,3,UserId,0,0.00
145,raw_catalog_ProductAllergen,48,Id,0,0.00
146,raw_catalog_ProductAllergen,48,AllergenId,0,0.00
147,raw_catalog_ProductAllergen,48,BakeryProductId,0,0.00
148,raw_catalog_ProductAllergen,48,Created,0,0.00
149,raw_catalog_ProductAllergen,48,Updated,0,0.00
150,raw_catalog_ProductAllergen,48,UserId,0,0.00
151,raw_catalog_ProductAttribute,3,Id,0,0.00
152,raw_catalog_ProductAttribute,3,Description,0,0.00
153,raw_catalog_ProductAttribute,3,Value,0,0.00
154,raw_catalog_ProductAttribute,3,Created,0,0.00
155,raw_catalog_ProductAttribute,3,Updated,0,0.00
156,raw_catalog_ProductAttribute,3,UserId,0,0.00
157,raw_catalog_ProductPrivateIngredient,12,Id,0,0.00
158,raw_catalog_ProductPrivateIngredient,12,BakeryProductId,0,0.00
159,raw_catalog_ProductPrivateIngredient,12,IngredientId,0,0.00
160,raw_catalog_ProductPrivateIngredient,12,Value,0,0.00
161,raw_catalog_ProductPrivateIngredient,12,Created,0,0.00
162,raw_catalog_ProductPrivateIngredient,12,Updated,0,0.00
163,raw_catalog_ProductPrivateIngredient,12,UserId,0,0.00
164,raw_catalog_ProductPublicIngredient,74,Id,0,0.00
165,raw_catalog_ProductPublicIngredient,74,BakeryProductId,0,0.00
166,raw_catalog_ProductPublicIngredient,74,IngredientId,0,0.00
167,raw_catalog_ProductPublicIngredient,74,Value,0,0.00
168,raw_catalog_ProductPublicIngredient,74,Created,0,0.00
169,raw_catalog_ProductPublicIngredient,74,Updated,0,0.00
170,raw_catalog_ProductPublicIngredient,74,UserId,0,0.00
171,raw_catalog_PublicIngredient,11,Id,0,0.00
172,raw_catalog_PublicIngredient,11,Name,0,0.00
173,raw_catalog_PublicIngredient,11,Unit,0,0.00
174,raw_catalog_PublicIngredient,11,Created,0,0.00
175,raw_catalog_PublicIngredient,11,Updated,0,0.00
176,raw_catalog_PublicIngredient,11,UserId,0,0.00
177,raw_claim_manager_ClaimEntityDeliveryItems,26,Id,0,0.00
178,raw_claim_manager_ClaimEntityDeliveryItems,26,Created,0,0.00
179,raw_claim_manager_ClaimEntityDeliveryItems,26,Updated,0,0.00
180,raw_claim_manager_ClaimEntityDeliveryItems,26,IssueType,0,0.00
181,raw_claim_manager_ClaimEntityDeliveryItems,26,DeliveryItemId,0,0.00
182,raw_claim_manager_ClaimEntityDeliveryItems,26,ClaimId,0,0.00
183,raw_claim_manager_ClaimEntityDeliveryItems,26,ProductName,0,0.00
184,raw_claim_manager_ClaimEntityDeliveryItems,26,OrderedQuantity,0,0.00
185,raw_claim_manager_ClaimEntityDeliveryItems,26,DeliveredQuantity,0,0.00
186,raw_claim_manager_ClaimEntityDeliveryItems,26,NumberOfProductsWithAcceptedClaim,0,0.00
187,raw_claim_manager_ClaimEntityDeliveryItems,26,UserId,0,0.00
188,raw_claim_manager_ClaimEntityDeliveryItems,26,ProductId,0,0.00
189,raw_claim_manager_ClaimEntityDeliveryItems,26,ClaimedQuantity,0,0.00
190,raw_claim_manager_ClaimItems,46,Id,0,0.00
191,raw_claim_manager_ClaimItems,46,ClaimEntityId,0,0.00
192,raw_claim_manager_ClaimItems,46,Notifier,0,0.00
193,raw_claim_manager_ClaimItems,46,Created,0,0.00
194,raw_claim_manager_ClaimItems,46,Updated,0,0.00
195,raw_claim_manager_ClaimItems,46,UserId,0,0.00
196,raw_claim_manager_ClaimItems,46,Type,0,0.00
197,raw_claim_manager_ClaimsEntity,34,Id,0,0.00
198,raw_claim_manager_ClaimsEntity,34,OrderId,0,0.00
199,raw_claim_manager_ClaimsEntity,34,DeliveryId,0,0.00
200,raw_claim_manager_ClaimsEntity,34,Description,0,0.00
201,raw_claim_manager_ClaimsEntity,34,Date,0,0.00
202,raw_claim_manager_ClaimsEntity,34,State,0,0.00
203,raw_claim_manager_ClaimsEntity,34,Type,0,0.00
204,raw_claim_manager_ClaimsEntity,34,AgreedDiscountId,0,0.00
205,raw_claim_manager_ClaimsEntity,34,AgreedReturnAmount,0,0.00
206,raw_claim_manager_ClaimsEntity,34,Created,0,0.00
207,raw_claim_manager_ClaimsEntity,34,Updated,0,0.00
208,raw_claim_manager_ClaimsEntity,34,UserId,0,0.00
209,raw_claim_manager_ClaimsEntity,34,ServicingBySiteId,0,0.00
210,raw_client_manager_Client,4,Id,0,0.00
211,raw_client_manager_Client,4,Name,0,0.00
212,raw_client_manager_Client,4,Description,0,0.00
213,raw_client_manager_Client,4,Street,0,0.00
214,raw_client_manager_Client,4,City,0,0.00
215,raw_client_manager_Client,4,Country,0,0.00
216,raw_client_manager_Client,4,ZipCode,0,0.00
217,raw_client_manager_Client,4,PictureFileName,0,0.00
218,raw_client_manager_Client,4,Created,0,0.00
219,raw_client_manager_Client,4,Updated,0,0.00
220,raw_client_manager_Client,4,UserId,0,0.00
221,raw_client_manager_Client,4,ModifiedByUserId,0,0.00
222,raw_client_manager_IndicatedBakery,6,Id,0,0.00
223,raw_client_manager_IndicatedBakery,6,BakeryName,0,0.00
224,raw_client_manager_IndicatedBakery,6,BakeryAddress,0,0.00
225,raw_client_manager_IndicatedBakery,6,MapInfo,0,0.00
226,raw_client_manager_Leave,24,Id,0,0.00
227,raw_client_manager_Leave,24,SiteId,0,0.00
228,raw_client_manager_Leave,24,DateFrom,0,0.00
229,raw_client_manager_Leave,24,DateTo,0,0.00
230,raw_client_manager_Leave,24,Type,0,0.00
231,raw_client_manager_Leave,24,Description,0,0.00
232,raw_client_manager_Leave,24,State,0,0.00
233,raw_client_manager_Leave,24,Created,0,0.00
234,raw_client_manager_Leave,24,Updated,0,0.00
235,raw_client_manager_Leave,24,UserId,0,0.00
236,raw_client_manager_Leave,24,ModifiedByUserId,0,0.00
237,raw_client_manager_Location,35,Id,0,0.00
238,raw_client_manager_Location,35,Name,0,0.00
239,raw_client_manager_Location,35,Description,0,0.00
240,raw_client_manager_Location,35,Created,0,0.00
241,raw_client_manager_Location,35,Updated,0,0.00
242,raw_client_manager_Location,35,UserId,0,0.00
243,raw_client_manager_Location,35,ModifiedByUserId,0,0.00
244,raw_client_manager_Location,35,Status,0,0.00
245,raw_client_manager_LocationSite,13,Id,0,0.00
246,raw_client_manager_LocationSite,13,SiteId,0,0.00
247,raw_client_manager_LocationSite,13,LocationId,0,0.00
248,raw_client_manager_LocationSite,13,Created,0,0.00
249,raw_client_manager_LocationSite,13,Updated,0,0.00
250,raw_client_manager_LocationSite,13,UserId,0,0.00
251,raw_client_manager_LocationSite,13,ModifiedByUserId,0,0.00
252,raw_client_manager_Person,8,Id,0,0.00
253,raw_client_manager_Person,8,ClientId,0,0.00
254,raw_client_manager_Person,8,Name,0,0.00
255,raw_client_manager_Person,8,Interview,0,0.00
256,raw_client_manager_Person,8,PictureLink,0,0.00
257,raw_client_manager_Person,8,Created,0,0.00
258,raw_client_manager_Person,8,Updated,0,0.00
259,raw_client_manager_Person,8,UserId,0,0.00
260,raw_client_manager_Person,8,ModifiedByUserId,0,0.00
261,raw_client_manager_PolygonVertex,234,Id,0,0.00
262,raw_client_manager_PolygonVertex,234,LocationId,0,0.00
263,raw_client_manager_PolygonVertex,234,Latitude,0,0.00
264,raw_client_manager_PolygonVertex,234,Longitude,0,0.00
265,raw_client_manager_PolygonVertex,234,Created,0,0.00
266,raw_client_manager_PolygonVertex,234,Updated,0,0.00
267,raw_client_manager_PolygonVertex,234,UserId,0,0.00
268,raw_client_manager_PolygonVertex,234,ModifiedByUserId,0,0.00
269,raw_client_manager_Site,8,Id,0,0.00
270,raw_client_manager_Site,8,Name,0,0.00
271,raw_client_manager_Site,8,Street,0,0.00
272,raw_client_manager_Site,8,Nr,0,0.00
273,raw_client_manager_Site,8,City,0,0.00
274,raw_client_manager_Site,8,State,0,0.00
275,raw_client_manager_Site,8,Country,0,0.00
276,raw_client_manager_Site,8,ZipCode,0,0.00
277,raw_client_manager_Site,8,ClientId,0,0.00
278,raw_client_manager_Site,8,SiteCoordinatesId,0,0.00
279,raw_client_manager_Site,8,PictureFileName,0,0.00
280,raw_client_manager_Site,8,Created,0,0.00
281,raw_client_manager_Site,8,Updated,0,0.00
282,raw_client_manager_Site,8,UserId,0,0.00
283,raw_client_manager_Site,8,ModifiedByUserId,0,0.00
284,raw_client_manager_SiteCoordinates,9,Id,0,0.00
285,raw_client_manager_SiteCoordinates,9,Latitude,0,0.00
286,raw_client_manager_SiteCoordinates,9,Longitude,0,0.00
287,raw_client_manager_SiteCoordinates,9,Created,0,0.00
288,raw_client_manager_SiteCoordinates,9,Updated,0,0.00
289,raw_client_manager_SiteCoordinates,9,UserId,0,0.00
290,raw_client_manager_SiteCoordinates,9,ModifiedByUserId,0,0.00
291,raw_customer_manager_Consents,3,Id,0,0.00
292,raw_customer_manager_Consents,3,Type,0,0.00
293,raw_customer_manager_Consents,3,Created,0,0.00
294,raw_customer_manager_Consents,3,Updated,0,0.00
295,raw_customer_manager_Consents,3,LinkToDocument,0,0.00
296,raw_customer_manager_Consents,3,UserId,0,0.00
297,raw_customer_manager_Consents,3,ModifiedByUserId,0,0.00
298,raw_customer_manager_Consents,3,Status,0,0.00
299,raw_customer_manager_Consents,3,Version,0,0.00
300,raw_customer_manager_Consents,3,GoLiveDate,0,0.00
301,raw_customer_manager_Consents,3,ObligationType,0,0.00
302,raw_customer_manager_Customer,176,Id,0,0.00
303,raw_customer_manager_Customer,176,Created,0,0.00
304,raw_customer_manager_Customer,176,Updated,0,0.00
305,raw_customer_manager_Customer,176,UserId,0,0.00
306,raw_customer_manager_Customer,176,ModifiedByUserId,0,0.00
307,raw_customer_manager_Customer,176,OtherRoleStatus,0,0.00
308,raw_customer_manager_Customer,176,CustomerState,0,0.00
309,raw_customer_manager_CustomerAddress,544,Id,0,0.00
310,raw_customer_manager_CustomerAddress,544,Longitude,0,0.00
311,raw_customer_manager_CustomerAddress,544,Latitude,0,0.00
312,raw_customer_manager_CustomerAddress,544,Created,0,0.00
313,raw_customer_manager_CustomerAddress,544,Updated,0,0.00
314,raw_customer_manager_CustomerAddress,544,UserId,0,0.00
315,raw_customer_manager_CustomerAddress,544,ModifiedByUserId,0,0.00
316,raw_customer_manager_CustomerAddress,544,CustomerId,0,0.00
317,raw_customer_manager_CustomerAddress,544,State,0,0.00
318,raw_customer_manager_CustomerConsent,471,Id,0,0.00
319,raw_customer_manager_CustomerConsent,471,CustomerId,0,0.00
320,raw_customer_manager_CustomerConsent,471,ConsentId,0,0.00
321,raw_customer_manager_CustomerConsent,471,Created,0,0.00
322,raw_customer_manager_CustomerConsent,471,Updated,0,0.00
323,raw_customer_manager_CustomerConsent,471,UserId,0,0.00
324,raw_customer_manager_CustomerConsent,471,ModifiedByUserId,0,0.00
325,raw_customer_manager_CustomerConsent,471,Status,0,0.00
326,raw_customer_manager_CustomerConsent,471,Date,0,0.00
327,raw_delivery_account_manager_Address,6,Id,0,0.00
328,raw_delivery_account_manager_Address,6,AddressName,0,0.00
329,raw_delivery_account_manager_Address,6,City,0,0.00
330,raw_delivery_account_manager_Address,6,DeliveryManId,0,0.00
331,raw_delivery_account_manager_Address,6,Created,0,0.00
332,raw_delivery_account_manager_Address,6,Updated,0,0.00
333,raw_delivery_account_manager_Address,6,UserId,0,0.00
334,raw_delivery_account_manager_BankAccount,2,Id,0,0.00
335,raw_delivery_account_manager_BankAccount,2,DeliveryManId,0,0.00
336,raw_delivery_account_manager_BankAccount,2,Created,0,0.00
337,raw_delivery_account_manager_BankAccount,2,Updated,0,0.00
338,raw_delivery_account_manager_BankAccount,2,UserId,0,0.00
339,raw_delivery_account_manager_DeliveryMan,6,Id,0,0.00
340,raw_delivery_account_manager_DeliveryMan,6,Name,0,0.00
341,raw_delivery_account_manager_DeliveryMan,6,SiteId,0,0.00
342,raw_delivery_account_manager_DeliveryMan,6,Created,0,0.00
343,raw_delivery_account_manager_DeliveryMan,6,Updated,0,0.00
344,raw_delivery_account_manager_DeliveryMan,6,UserId,0,0.00
345,raw_delivery_account_manager_DeliveryManLocati...,493,Id,0,0.00
346,raw_delivery_account_manager_DeliveryManLocati...,493,LocationId,0,0.00
347,raw_delivery_account_manager_DeliveryManLocati...,493,Date,0,0.00
348,raw_delivery_account_manager_DeliveryManLocati...,493,DeliveryManId,0,0.00
349,raw_delivery_account_manager_DeliveryManLocati...,493,Created,0,0.00
350,raw_delivery_account_manager_DeliveryManLocati...,493,Updated,0,0.00
351,raw_delivery_account_manager_DeliveryManLocati...,493,UserId,0,0.00
352,raw_delivery_account_manager_DeliveryManLocati...,493,SiteId,0,0.00
353,raw_delivery_account_manager_DeliveryManUnavai...,17,Id,0,0.00
354,raw_delivery_account_manager_DeliveryManUnavai...,17,DeliveryManId,0,0.00
355,raw_delivery_account_manager_DeliveryManUnavai...,17,DateFrom,0,0.00
356,raw_delivery_account_manager_DeliveryManUnavai...,17,DateTo,0,0.00
357,raw_delivery_account_manager_DeliveryManUnavai...,17,Created,0,0.00
358,raw_delivery_account_manager_DeliveryManUnavai...,17,Updated,0,0.00
359,raw_delivery_account_manager_DeliveryManUnavai...,17,State,0,0.00
360,raw_delivery_account_manager_DeliveryManUnavai...,17,UserId,0,0.00
361,raw_delivery_manager_AreaOfDeliveryForDate,578,Id,0,0.00
362,raw_delivery_manager_AreaOfDeliveryForDate,578,Date,0,0.00
363,raw_delivery_manager_AreaOfDeliveryForDate,578,Name,0,0.00
364,raw_delivery_manager_AreaOfDeliveryForDate,578,EstimatedNoOfDelivery,0,0.00
365,raw_delivery_manager_AreaOfDeliveryForDate,578,LocationId,0,0.00
366,raw_delivery_manager_AreaOfDeliveryForDate,578,SiteId,0,0.00
367,raw_delivery_manager_AreaOfDeliveryForDate,578,Created,0,0.00

NULL DATA REPORT - LAYER: SILVER

,table_name,row_count,column_name,null_count,null_percentage
0,stg_payment,2235,error,2234,99.96
1,stg_payment,2235,discounted_amount,2168,97.00
2,stg_payment,2235,id_discount,2167,96.96
3,stg_discount,21,id_customer,19,90.48
4,stg_delivery_items,1741,packed_quantity,1552,89.14
5,stg_bakery_offer,145,next_version_id,121,83.45
6,stg_payment,2235,id_client,1681,75.21
7,stg_refund,1063,base_amount,767,72.15
8,stg_bakery_offer,145,previous_version_offer_id,78,53.79
9,stg_bakery_product,83,id_previous_version_product,41,49.40
10,stg_bakery_product,83,id_modified_version_product,41,49.40
11,stg_discount,21,id_client,10,47.62
12,stg_payment,2235,id_delivery,974,43.58
13,stg_deliveries,1162,id_delivery_man,84,7.23
14,stg_bakery_order_items,9454,id_planner_item,392,4.15
15,stg_allergen,15,id_allergen,0,0.00
16,stg_allergen,15,name,0,0.00
17,stg_allergen,15,is_used,0,0.00
18,stg_allergen,15,created_at,0,0.00
19,stg_allergen,15,updated_at,0,0.00
20,stg_allergen,15,user_id,0,0.00
21,stg_area_of_delivery_for_date,578,id_area_of_delivery_for_date,0,0.00
22,stg_area_of_delivery_for_date,578,delivery_date,0,0.00
23,stg_area_of_delivery_for_date,578,id_location,0,0.00
24,stg_area_of_delivery_for_date,578,id_site,0,0.00
25,stg_area_of_delivery_for_date,578,created_at,0,0.00
26,stg_area_of_delivery_for_date,578,updated_at,0,0.00
27,stg_bakery_offer,145,id_offer,0,0.00
28,stg_bakery_offer,145,name,0,0.00
29,stg_bakery_offer,145,price,0,0.00
30,stg_bakery_offer,145,state,0,0.00
31,stg_bakery_offer,145,type,0,0.00
32,stg_bakery_offer,145,available_stock,0,0.00
33,stg_bakery_offer,145,is_available,0,0.00
34,stg_bakery_offer,145,platform_client_id,0,0.00
35,stg_bakery_offer,145,vat_rate_id,0,0.00
36,stg_bakery_offer,145,vat,0,0.00
37,stg_bakery_offer,145,created_at,0,0.00
38,stg_bakery_offer,145,updated_at,0,0.00
39,stg_bakery_offer,145,user_id,0,0.00
40,stg_bakery_order_items,9454,id_order_item,0,0.00
41,stg_bakery_order_items,9454,quantity,0,0.00
42,stg_bakery_order_items,9454,id_order,0,0.00
43,stg_bakery_order_items,9454,id_bought_offer_instance,0,0.00
44,stg_bakery_order_items,9454,modified_by_hand,0,0.00
45,stg_bakery_order_items,9454,order_item_state_id,0,0.00
46,stg_bakery_order_items,9454,order_item_state,0,0.00
47,stg_bakery_order_items,9454,user_id,0,0.00
48,stg_bakery_order_items,9454,created_at,0,0.00
49,stg_bakery_order_items,9454,updated_at,0,0.00
50,stg_bakery_orders,5743,id_order,0,0.00
51,stg_bakery_orders,5743,id_customer_address,0,0.00
52,stg_bakery_orders,5743,date_order,0,0.00
53,stg_bakery_orders,5743,order_state_id,0,0.00
54,stg_bakery_orders,5743,order_state,0,0.00
55,stg_bakery_orders,5743,user_id,0,0.00
56,stg_bakery_orders,5743,id_site,0,0.00
57,stg_bakery_orders,5743,id_location,0,0.00
58,stg_bakery_orders,5743,created_at,0,0.00
59,stg_bakery_orders,5743,updated_at,0,0.00
60,stg_bakery_product,83,id_product,0,0.00
61,stg_bakery_product,83,name,0,0.00
62,stg_bakery_product,83,description,0,0.00
63,stg_bakery_product,83,state,0,0.00
64,stg_bakery_product,83,picture_file_name,0,0.00
65,stg_bakery_product,83,id_product_type,0,0.00
66,stg_bakery_product,83,id_client,0,0.00
67,stg_bakery_product,83,weight,0,0.00
68,stg_bakery_product,83,created_at,0,0.00
69,stg_bakery_product,83,updated_at,0,0.00
70,stg_bakery_product,83,user_id,0,0.00
71,stg_bakery_product_type,4,id_product_type,0,0.00
72,stg_bakery_product_type,4,name,0,0.00
73,stg_bakery_product_type,4,picture_file_name,0,0.00
74,stg_bakery_product_type,4,product_type_display_order,0,0.00
75,stg_bakery_product_type,4,created_at,0,0.00
76,stg_bakery_product_type,4,updated_at,0,0.00
77,stg_bakery_product_type,4,user_id,0,0.00
78,stg_bought_offer_instance,1805,id_bought_offer_instance,0,0.00
79,stg_bought_offer_instance,1805,id_offer,0,0.00
80,stg_bought_offer_instance,1805,offer_name,0,0.00
81,stg_bought_offer_instance,1805,price,0,0.00
82,stg_bought_offer_instance,1805,vat,0,0.00
83,stg_bought_offer_instance,1805,vat_rate_id,0,0.00
84,stg_bought_offer_instance,1805,bought_offer_instance_type_id,0,0.00
85,stg_bought_offer_instance,1805,bought_offer_instance_type,0,0.00
86,stg_bought_offer_instance,1805,picture_file_name,0,0.00
87,stg_bought_offer_instance,1805,user_id,0,0.00
88,stg_bought_offer_instance,1805,created_at,0,0.00
89,stg_bought_offer_instance,1805,updated_at,0,0.00
90,stg_client,4,id_client,0,0.00
91,stg_client,4,name,0,0.00
92,stg_client,4,description,0,0.00
93,stg_client,4,nip,0,0.00
94,stg_client,4,street,0,0.00
95,stg_client,4,city,0,0.00
96,stg_client,4,country,0,0.00
97,stg_client,4,zip_code,0,0.00
98,stg_client,4,picture_file_name,0,0.00
99,stg_client,4,created_at,0,0.00
100,stg_client,4,updated_at,0,0.00
101,stg_client,4,user_id,0,0.00
102,stg_client,4,modified_by_user_id,0,0.00
103,stg_client,4,full_formal_name,0,0.00
104,stg_client,4,story,0,0.00
105,stg_customer,176,id_customer,0,0.00
106,stg_customer,176,name,0,0.00
107,stg_customer,176,customer_state,0,0.00
108,stg_customer,176,user_id,0,0.00
109,stg_customer,176,other_role_state,0,0.00
110,stg_customer,176,created_at,0,0.00
111,stg_customer,176,updated_at,0,0.00
112,stg_customer_address,544,id_customer_address,0,0.00
113,stg_customer_address,544,id_customer,0,0.00
114,stg_customer_address,544,address_name,0,0.00
115,stg_customer_address,544,address,0,0.00
116,stg_customer_address,544,longitude,0,0.00
117,stg_customer_address,544,latitude,0,0.00
118,stg_customer_address,544,geo_point,0,0.00
119,stg_customer_address,544,state,0,0.00
120,stg_customer_consent,471,id_customer_consent,0,0.00
121,stg_customer_consent,471,id_customer,0,0.00
122,stg_customer_consent,471,id_consent,0,0.00
123,stg_customer_consent,471,state,0,0.00
124,stg_customer_consent,471,consent_date,0,0.00
125,stg_deliveries,1162,id_delivery,0,0.00
126,stg_deliveries,1162,id_customer_address,0,0.00
127,stg_deliveries,1162,id_area_of_delivery_for_date,0,0.00
128,stg_deliveries,1162,state_id,0,0.00
129,stg_deliveries,1162,state,0,0.00
130,stg_deliveries,1162,id_site,0,0.00
131,stg_deliveries,1162,id_order,0,0.00
132,stg_deliveries,1162,created_at,0,0.00
133,stg_deliveries,1162,updated_at,0,0.00
134,stg_delivery_items,1741,id_delivery_item,0,0.00
135,stg_delivery_items,1741,id_delivery,0,0.00
136,stg_delivery_items,1741,id_product,0,0.00
137,stg_delivery_items,1741,state_id,0,0.00
138,stg_delivery_items,1741,state,0,0.00
139,stg_delivery_items,1741,planned_quantity,0,0.00
140,stg_delivery_items,1741,product_name,0,0.00
141,stg_delivery_items,1741,product_price,0,0.00
142,stg_delivery_items,1741,created_at,0,0.00
143,stg_delivery_items,1741,modified_at,0,0.00
144,stg_delivery_man,6,id_delivery_man,0,0.00
145,stg_delivery_man,6,name,0,0.00
146,stg_delivery_man,6,id_site,0,0.00
147,stg_delivery_man,6,created_at,0,0.00
148,stg_delivery_man,6,updated_at,0,0.00
149,stg_discount,21,id_discount,0,0.00
150,stg_discount,21,discount_percentage,0,0.00
151,stg_discount,21,discount_flat_rate,0,0.00
152,stg_discount,21,discount_code,0,0.00
153,stg_discount,21,active_from,0,0.00
154,stg_discount,21,active_to,0,0.00
155,stg_discount,21,use_limit_globally,0,0.00
156,stg_discount,21,use_limit_per_user,0,0.00
157,stg_discount,21,minimal_transaction_amount,0,0.00
158,stg_discount,21,maximum_transaction_amount,0,0.00
159,stg_discount,21,money_limit_globally,0,0.00
160,stg_discount,21,money_limit_per_user,0,0.00
161,stg_discount,21,only_for_first_purchase,0,0.00
162,stg_discount,21,link_to_terms,0,0.00
163,stg_discount,21,created_at,0,0.00
164,stg_discount,21,updated_at,0,0.00
165,stg_google_competitors,483,id_competitor,0,0.00
166,stg_google_competitors,483,name,0,0.00
167,stg_google_competitors,483,address,0,0.00
168,stg_google_competitors,483,latitude,0,0.00
169,stg_google_competitors,483,longitude,0,0.00
170,stg_google_competitors,483,geo_point,0,0.00
171,stg_google_competitors,483,competitor_type,0,0.00
172,stg_google_competitors,483,extracted_at,0,0.00
173,stg_location,35,id_location,0,0.00
174,stg_location,35,name,0,0.00
175,stg_location,35,description,0,0.00
176,stg_location,35,state,0,0.00
177,stg_location,35,created_at,0,0.00
178,stg_location,35,updated_at,0,0.00
179,stg_location,35,user_id,0,0.00
180,stg_location,35,modified_by_user_id,0,0.00
181,stg_location_site,13,id_location_site,0,0.00
182,stg_location_site,13,id_location,0,0.00
183,stg_location_site,13,id_site,0,0.00
184,stg_location_site,13,created_at,0,0.00
185,stg_location_site,13,updated_at,0,0.00
186,stg_location_site,13,user_id,0,0.00
187,stg_location_site,13,modified_by_user_id,0,0.00
188,stg_nutrition,83,id_nutrition,0,0.00
189,stg_nutrition,83,id_product,0,0.00
190,stg_nutrition,83,calories,0,0.00
191,stg_nutrition,83,total_fats,0,0.00
192,stg_nutrition,83,saturated_fats,0,0.00
193,stg_nutrition,83,total_carbohydrates,0,0.00
194,stg_nutrition,83,sugar,0,0.00
195,stg_nutrition,83,protein,0,0.00
196,stg_nutrition,83,sodium,0,0.00
197,stg_nutrition,83,created_at,0,0.00
198,stg_nutrition,83,updated_at,0,0.00
199,stg_nutrition,83,user_id,0,0.00
200,stg_offer_product,151,id_offer_product,0,0.00
201,stg_offer_product,151,id_product,0,0.00
202,stg_offer_product,151,product_price,0,0.00
203,stg_offer_product,151,product_name,0,0.00
204,stg_offer_product,151,picture_file_name,0,0.00
205,stg_offer_product,151,id_offer,0,0.00
206,stg_offer_product,151,product_count,0,0.00
207,stg_offer_product,151,is_available_in_offer,0,0.00
208,stg_offer_product,151,is_available_in_offer_site,0,0.00
209,stg_offer_product,151,product_in_offer_price,0,0.00
210,stg_offer_product,151,vat_for_product_in_offer,0,0.00
211,stg_offer_product,151,created_at,0,0.00
212,stg_offer_product,151,updated_at,0,0.00
213,stg_offer_product,151,user_id,0,0.00
214,stg_payment,2235,id_payment,0,0.00
215,stg_payment,2235,created_at,0,0.00
216,stg_payment,2235,updated_at,0,0.00
217,stg_payment,2235,status_id,0,0.00
218,stg_payment,2235,status,0,0.00
219,stg_payment,2235,amount,0,0.00
220,stg_payment,2235,id_order,0,0.00
221,stg_payment,2235,user_id,0,0.00
222,stg_payment,2235,id_payment_method,0,0.00
223,stg_payment,2235,list_of_order_items,0,0.00
224,stg_payment,2235,for_manual_handling,0,0.00
225,stg_payment,2235,payment_type_id,0,0.00
226,stg_payment,2235,payment_type,0,0.00
227,stg_payment_method,187,id_payment_method,0,0.00
228,stg_payment_method,187,type,0,0.00
229,stg_payment_method,187,currency,0,0.00
230,stg_payment_method,187,state,0,0.00
231,stg_payment_method,187,card_brand,0,0.00
232,stg_payment_method,187,mobile,0,0.00
233,stg_payment_method,187,created_at,0,0.00
234,stg_payment_method,187,updated_at,0,0.00
235,stg_payment_method,187,user_id,0,0.00
236,stg_payment_method,187,id_customer,0,0.00
237,stg_payment_method,187,marked_as_primary_on_creation,0,0.00
238,stg_planner_item,1931,id_planner_item,0,0.00
239,stg_planner_item,1931,planner_item_state_id,0,0.00
240,stg_planner_item,1931,planner_item_state,0,0.00
241,stg_planner_item,1931,quantity,0,0.00
242,stg_planner_item,1931,id_customer_address,0,0.00
243,stg_planner_item,1931,day_index,0,0.00
244,stg_planner_item,1931,day_name,0,0.00
245,stg_planner_item,1931,next_version,0,0.00
246,stg_planner_item,1931,previous_version,0,0.00
247,stg_planner_item,1931,start_date,0,0.00
248,stg_planner_item,1931,end_date,0,0.00
249,stg_planner_item,1931,id_bought_offer_instance,0,0.00
250,stg_planner_item,1931,user_id,0,0.00
251,stg_planner_item,1931,id_site,0,0.00
252,stg_planner_item,1931,id_location,0,0.00
253,stg_planner_item,1931,created_at,0,0.00
254,stg_planner_item,1931,updated_at,0,0.00
255,stg_polygon_vertex,234,id_polygon_vertex,0,0.00
256,stg_polygon_vertex,234,id_location,0,0.00
257,stg_polygon_vertex,234,latitude,0,0.00
258,stg_polygon_vertex,234,longitude,0,0.00
259,stg_polygon_vertex,234,created_at,0,0.00
260,stg_polygon_vertex,234,updated_at,0,0.00
261,stg_polygon_vertex,234,user_id,0,0.00
262,stg_polygon_vertex,234,modified_by_user_id,0,0.00
263,stg_private_ingredient,3,id_ingredient,0,0.00
264,stg_private_ingredient,3,platform_client_id,0,0.00
265,stg_private_ingredient,3,name,0,0.00
266,stg_private_ingredient,3,unit,0,0.00
267,stg_private_ingredient,3,created_at,0,0.00
268,stg_private_ingredient,3,updated_at,0,0.00
269,stg_private_ingredient,3,user_id,0,0.00
270,stg_product_allergen,48,id_product_allergen,0,0.00
271,stg_product_allergen,48,id_allergen,0,0.00
272,stg_product_allergen,48,id_product,0,0.00
273,stg_product_allergen,48,created_at,0,0.00
274,stg_product_allergen,48,updated_at,0,0.00
275,stg_product_allergen,48,user_id,0,0.00
276,stg_product_private_ingredient,12,id_product_ingredient,0,0.00
277,stg_product_private_ingredient,12,id_product,0,0.00
278,stg_product_private_ingredient,12,id_ingredient,0,0.00
279,stg_product_private_ingredient,12,value,0,0.00
280,stg_product_private_ingredient,12,created_at,0,0.00
281,stg_product_private_ingredient,12,updated_at,0,0.00
282,stg_product_private_ingredient,12,user_id,0,0.00
283,stg_product_public_ingredient,74,id_product_ingredient,0,0.00
284,stg_product_public_ingredient,74,id_product,0,0.00
285,stg_product_public_ingredient,74,id_ingredient,0,0.00
286,stg_product_public_ingredient,74,value,0,0.00
287,stg_product_public_ingredient,74,created_at,0,0.00
288,stg_product_public_ingredient,74,updated_at,0,0.00
289,stg_product_public_ingredient,74,user_id,0,0.00
290,stg_public_ingredient,11,id_ingredient,0,0.00
291,stg_public_ingredient,11,name,0,0.00
292,stg_public_ingredient,11,unit,0,0.00
293,stg_public_ingredient,11,created_at,0,0.00
294,stg_public_ingredient,11,updated_at,0,0.00
295,stg_public_ingredient,11,user_id,0,0.00
296,stg_refund,1063,id_refund,0,0.00
297,stg_refund,1063,id_payment,0,0.00
298,stg_refund,1063,id_claim,0,0.00
299,stg_refund,1063,refund_state_id,0,0.00
300,stg_refund,1063,refund_state,0,0.00
301,stg_refund,1063,refund_type_id,0,0.00
302,stg_refund,1063,refund_type,0,0.00
303,stg_refund,1063,amount,0,0.00
304,stg_refund,1063,description,0,0.00
305,stg_refund,1063,user_id,0,0.00
306,stg_refund,1063,created_at,0,0.00
307,stg_refund,1063,modified_at,0,0.00
308,stg_refund_items,1132,id_refund_item,0,0.00
309,stg_refund_items,1132,id_refund,0,0.00
310,stg_refund_items,1132,id_product,0,0.00
311,stg_refund_items,1132,missing_product_quantity,0,0.00
312,stg_refund_items,1132,amount,0,0.00
313,stg_refund_items,1132,vat_amount,0,0.00
314,stg_refund_items,1132,user_id,0,0.00
315,stg_refund_items,1132,created_at,0,0.00
316,stg_refund_items,1132,modified_at,0,0.00
317,stg_site,8,id_site,0,0.00
318,stg_site,8,name,0,0.00
319,stg_site,8,street,0,0.00
320,stg_site,8,nr,0,0.00
321,stg_site,8,city,0,0.00
322,stg_site,8,state,0,0.00
323,stg_site,8,country,0,0.00
324,stg_site,8,zip_code,0,0.00
325,stg_site,8,id_client,0,0.00
326,stg_site,8,id_coordinates,0,0.00
327,stg_site,8,picture_file_name,0,0.00
328,stg_site,8,created_at,0,0.00
329,stg_site,8,updated_at,0,0.00
330,stg_site,8,user_id,0,0.00
331,stg_site,8,modified_by_user_id,0,0.00
332,stg_site_coordinates,9,id_coordinates,0,0.00
333,stg_site_coordinates,9,latitude,0,0.00
334,stg_site_coordinates,9,longitude,0,0.00
335,stg_site_coordinates,9,geo_point,0,0.00
336,stg_site_coordinates,9,created_at,0,0.00
337,stg_site_coordinates,9,updated_at,0,0.00
338,stg_site_coordinates,9,user_id,0,0.00
339,stg_site_coordinates,9,modified_by_user_id,0,0.00

NULL DATA REPORT - LAYER: GOLD

,table_name,row_count,column_name,null_count,null_percentage
0,bridge_location_site,13,sk_location_site,0,0.0
1,bridge_location_site,13,id_location_site,0,0.0
2,bridge_location_site,13,id_location,0,0.0
3,bridge_location_site,13,id_site,0,0.0
4,bridge_offer_product,151,sk_offer_product,0,0.0
5,bridge_offer_product,151,id_offer_product,0,0.0
6,bridge_offer_product,151,id_offer,0,0.0
7,bridge_offer_product,151,id_product,0,0.0
8,bridge_offer_product,151,product_count,0,0.0
9,bridge_offer_product,151,product_in_offer_count,0,0.0
10,bridge_product_allergen,48,sk_product_allergen,0,0.0
11,bridge_product_allergen,48,id_product_allergen,0,0.0
12,bridge_product_allergen,48,id_product,0,0.0
13,bridge_product_allergen,48,id_allergen,0,0.0
14,bridge_product_ingredient,86,sk_product_ingredient,0,0.0
15,bridge_product_ingredient,86,id_product_ingredient,0,0.0
16,bridge_product_ingredient,86,id_product,0,0.0
17,bridge_product_ingredient,86,id_ingredient,0,0.0
18,bridge_product_ingredient,86,value,0,0.0
19,bridge_product_ingredient,86,is_public,0,0.0
20,dim_allergen,16,sk_allergen,0,0.0
21,dim_allergen,16,id_allergen,0,0.0
22,dim_allergen,16,name,0,0.0
23,dim_competitor,481,sk_competitor,0,0.0
24,dim_competitor,481,id_competitor,0,0.0
25,dim_competitor,481,name,0,0.0
26,dim_competitor,481,address,0,0.0
27,dim_competitor,481,latitude,0,0.0
28,dim_competitor,481,longitude,0,0.0
29,dim_competitor,481,geo_point,0,0.0
30,dim_competitor,481,competitor_type,0,0.0
31,dim_competitor,481,extracted_at,0,0.0
32,dim_consent_profile,65,sk_consent_profile,0,0.0
33,dim_consent_profile,65,rodo_state_id,0,0.0
34,dim_consent_profile,65,rodo_state,0,0.0
35,dim_consent_profile,65,terms_state_id,0,0.0
36,dim_consent_profile,65,terms_state,0,0.0
37,dim_consent_profile,65,marketing_state_id,0,0.0
38,dim_consent_profile,65,marketing_state,0,0.0
39,dim_customer,177,sk_customer,0,0.0
40,dim_customer,177,id_customer,0,0.0
41,dim_customer,177,sk_consent_profile,0,0.0
42,dim_customer,177,name,0,0.0
43,dim_customer,177,customer_state_id,0,0.0
44,dim_customer,177,customer_state,0,0.0
45,dim_customer,177,account_created_at,0,0.0
46,dim_customer,177,valid_from,0,0.0
47,dim_customer,177,valid_to,0,0.0
48,dim_customer,177,is_current,0,0.0
49,dim_customer_address,545,sk_customer_address,0,0.0
50,dim_customer_address,545,id_customer_address,0,0.0
51,dim_customer_address,545,id_customer,0,0.0
52,dim_customer_address,545,address_name,0,0.0
53,dim_customer_address,545,address,0,0.0
54,dim_customer_address,545,longitude,0,0.0
55,dim_customer_address,545,latitude,0,0.0
56,dim_customer_address,545,geo_point,0,0.0
57,dim_customer_address,545,additional_information,0,0.0
58,dim_customer_address,545,dist_to_nearest_own_site_m,0,0.0
59,dim_customer_address,545,dist_to_nearest_comp_bakery_m,0,0.0
60,dim_customer_address,545,dist_to_nearest_comp_supermarket_m,0,0.0
61,dim_customer_address,545,comp_bakery_count_300m,0,0.0
62,dim_customer_address,545,comp_bakery_count_500m,0,0.0
63,dim_customer_address,545,comp_bakery_count_1000m,0,0.0
64,dim_customer_address,545,comp_bakery_count_2000m,0,0.0
65,dim_customer_address,545,comp_supermarket_count_500m,0,0.0
66,dim_customer_address,545,comp_supermarket_count_1000m,0,0.0
67,dim_customer_address,545,comp_supermarket_count_2000m,0,0.0
68,dim_customer_address,545,comp_supermarket_count_3000m,0,0.0
69,dim_customer_address,545,own_site_count_300m,0,0.0
70,dim_customer_address,545,own_site_count_500m,0,0.0
71,dim_customer_address,545,own_site_count_1000m,0,0.0
72,dim_customer_address,545,own_site_count_2000m,0,0.0
73,dim_customer_address,545,own_site_count_3000m,0,0.0
74,dim_customer_address,545,state_id,0,0.0
75,dim_customer_address,545,state,0,0.0
76,dim_date,2558,sk_date,0,0.0
77,dim_date,2558,year,0,0.0
78,dim_date,2558,quarter,0,0.0
79,dim_date,2558,week,0,0.0
80,dim_date,2558,month_number,0,0.0
81,dim_date,2558,month_name,0,0.0
82,dim_date,2558,weekday_number,0,0.0
83,dim_date,2558,weekday_name,0,0.0
84,dim_date,2558,is_weekend,0,0.0
85,dim_date,2558,is_holiday,0,0.0
86,dim_date,2558,is_working,0,0.0
87,dim_delivery_man,7,sk_delivery_man,0,0.0
88,dim_delivery_man,7,id_delivery_man,0,0.0
89,dim_delivery_man,7,name,0,0.0
90,dim_delivery_man,7,id_site,0,0.0
91,dim_delivery_man,7,valid_from,0,0.0
92,dim_delivery_man,7,valid_to,0,0.0
93,dim_delivery_man,7,is_current,0,0.0
94,dim_discount,22,sk_discount,0,0.0
95,dim_discount,22,id_discount,0,0.0
96,dim_discount,22,discount_percentage,0,0.0
97,dim_discount,22,discount_flat_rate,0,0.0
98,dim_discount,22,discount_code,0,0.0
99,dim_discount,22,valid_from,0,0.0
100,dim_discount,22,valid_to,0,0.0
101,dim_discount,22,is_current,0,0.0
102,dim_discount,22,use_limit_globally,0,0.0
103,dim_discount,22,use_limit_per_user,0,0.0
104,dim_discount,22,minimal_transaction_amount,0,0.0
105,dim_discount,22,only_for_first_purchase,0,0.0
106,dim_ingredient,15,sk_ingredient,0,0.0
107,dim_ingredient,15,id_ingredient,0,0.0
108,dim_ingredient,15,name,0,0.0
109,dim_ingredient,15,unit,0,0.0
110,dim_ingredient,15,is_public,0,0.0
111,dim_location,36,sk_location,0,0.0
112,dim_location,36,id_location,0,0.0
113,dim_location,36,name,0,0.0
114,dim_location,36,description,0,0.0
115,dim_location,36,state_id,0,0.0
116,dim_location,36,state,0,0.0
117,dim_location,36,vertexes,0,0.0
118,dim_location,36,valid_from,0,0.0
119,dim_location,36,valid_to,0,0.0
120,dim_location,36,is_current,0,0.0
121,dim_offer,146,sk_offer,0,0.0
122,dim_offer,146,id_offer,0,0.0
123,dim_offer,146,name,0,0.0
124,dim_offer,146,price,0,0.0
125,dim_offer,146,state_id,0,0.0
126,dim_offer,146,state,0,0.0
127,dim_offer,146,type_id,0,0.0
128,dim_offer,146,type,0,0.0
129,dim_offer,146,vat,0,0.0
130,dim_offer,146,valid_from,0,0.0
131,dim_offer,146,valid_to,0,0.0
132,dim_offer,146,is_current,0,0.0
133,dim_payment_method,188,sk_payment_method,0,0.0
134,dim_payment_method,188,id_payment_method,0,0.0
135,dim_payment_method,188,type_id,0,0.0
136,dim_payment_method,188,type,0,0.0
137,dim_payment_method,188,currency,0,0.0
138,dim_payment_method,188,card_brand,0,0.0
139,dim_payment_method,188,mobile,0,0.0
140,dim_payment_method,188,state_id,0,0.0
141,dim_payment_method,188,state,0,0.0
142,dim_product,84,sk_product,0,0.0
143,dim_product,84,id_product,0,0.0
144,dim_product,84,name,0,0.0
145,dim_product,84,description,0,0.0
146,dim_product,84,state_id,0,0.0
147,dim_product,84,state,0,0.0
148,dim_product,84,product_type_name,0,0.0
149,dim_product,84,weight,0,0.0
150,dim_product,84,calories,0,0.0
151,dim_product,84,total_fats,0,0.0
152,dim_product,84,saturated_fats,0,0.0
153,dim_product,84,total_carbohydrates,0,0.0
154,dim_product,84,sugar,0,0.0
155,dim_product,84,protein,0,0.0
156,dim_product,84,sodium,0,0.0
157,dim_product,84,valid_from,0,0.0
158,dim_product,84,valid_to,0,0.0
159,dim_product,84,is_current,0,0.0
160,dim_site,9,sk_site,0,0.0
161,dim_site,9,id_site,0,0.0
162,dim_site,9,id_client,0,0.0
163,dim_site,9,id_coordinates,0,0.0
164,dim_site,9,client_name,0,0.0
165,dim_site,9,client_description,0,0.0
166,dim_site,9,client_street,0,0.0
167,dim_site,9,client_city,0,0.0
168,dim_site,9,client_country,0,0.0
169,dim_site,9,client_zip_code,0,0.0
170,dim_site,9,client_full_formal_name,0,0.0
171,dim_site,9,name,0,0.0
172,dim_site,9,street,0,0.0
173,dim_site,9,nr,0,0.0
174,dim_site,9,city,0,0.0
175,dim_site,9,state,0,0.0
176,dim_site,9,country,0,0.0
177,dim_site,9,zip_code,0,0.0
178,dim_site,9,latitude,0,0.0
179,dim_site,9,longitude,0,0.0
180,dim_site,9,geo_point,0,0.0
181,dim_site,9,valid_from,0,0.0
182,dim_site,9,valid_to,0,0.0
183,dim_site,9,is_current,0,0.0
184,fact_delivery_item,1741,sk_delivery_item,0,0.0
185,fact_delivery_item,1741,id_delivery_item,0,0.0
186,fact_delivery_item,1741,id_customer_address,0,0.0
187,fact_delivery_item,1741,id_delivery_man,0,0.0
188,fact_delivery_item,1741,id_product,0,0.0
189,fact_delivery_item,1741,id_delivery,0,0.0
190,fact_delivery_item,1741,id_site,0,0.0
191,fact_delivery_item,1741,id_customer,0,0.0
192,fact_delivery_item,1741,id_location,0,0.0
193,fact_delivery_item,1741,id_order,0,0.0
194,fact_delivery_item,1741,sk_location,0,0.0
195,fact_delivery_item,1741,sk_customer,0,0.0
196,fact_delivery_item,1741,sk_delivery_man,0,0.0
197,fact_delivery_item,1741,sk_site,0,0.0
198,fact_delivery_item,1741,sk_customer_address,0,0.0
199,fact_delivery_item,1741,sk_product,0,0.0
200,fact_delivery_item,1741,sk_date_delivery,0,0.0
201,fact_delivery_item,1741,sk_date_delivery_created,0,0.0
202,fact_delivery_item,1741,sk_date_delivery_modified,0,0.0
203,fact_delivery_item,1741,planned_quantity,0,0.0
204,fact_delivery_item,1741,packed_quantity,0,0.0
205,fact_delivery_item,1741,product_price,0,0.0
206,fact_delivery_item,1741,planned_amount,0,0.0
207,fact_delivery_item,1741,packed_amount,0,0.0
208,fact_delivery_item,1741,delivery_state_id,0,0.0
209,fact_delivery_item,1741,delivery_state,0,0.0
210,fact_delivery_item,1741,delivery_item_state_id,0,0.0
211,fact_delivery_item,1741,delivery_item_state,0,0.0
212,fact_delivery_item,1741,is_shortage,0,0.0
213,fact_order_item,9454,sk_order_item,0,0.0
214,fact_order_item,9454,id_order_item,0,0.0
215,fact_order_item,9454,id_order,0,0.0
216,fact_order_item,9454,id_bought_offer_instance,0,0.0
217,fact_order_item,9454,id_customer_address,0,0.0
218,fact_order_item,9454,id_location,0,0.0
219,fact_order_item,9454,id_site,0,0.0
220,fact_order_item,9454,id_offer,0,0.0
221,fact_order_item,9454,id_customer,0,0.0
222,fact_order_item,9454,id_planner_item,0,0.0
223,fact_order_item,9454,sk_date_order,0,0.0
224,fact_order_item,9454,sk_date_order_created,0,0.0
225,fact_order_item,9454,sk_date_order_modified,0,0.0
226,fact_order_item,9454,sk_offer,0,0.0
227,fact_order_item,9454,sk_customer_address,0,0.0
228,fact_order_item,9454,sk_location,0,0.0
229,fact_order_item,9454,sk_site,0,0.0
230,fact_order_item,9454,sk_customer,0,0.0
231,fact_order_item,9454,price,0,0.0
232,fact_order_item,9454,quantity,0,0.0
233,fact_order_item,9454,vat,0,0.0
234,fact_order_item,9454,gross_amount,0,0.0
235,fact_order_item,9454,net_amount,0,0.0
236,fact_order_item,9454,vat_amount,0,0.0
237,fact_order_item,9454,modified_by_hand,0,0.0
238,fact_order_item,9454,bought_offer_instance_type_id,0,0.0
239,fact_order_item,9454,bought_offer_instance_type,0,0.0
240,fact_order_item,9454,order_item_state_id,0,0.0
241,fact_order_item,9454,order_item_state,0,0.0
242,fact_order_item,9454,order_state_id,0,0.0
243,fact_order_item,9454,order_state,0,0.0
244,fact_order_item,9454,weather_morning_precip_prob,0,0.0
245,fact_order_item,9454,weather_morning_precip_sum_mm,0,0.0
246,fact_order_item,9454,weather_morning_was_rainy,0,0.0
247,fact_payment,2235,sk_payment,0,0.0
248,fact_payment,2235,id_payment,0,0.0
249,fact_payment,2235,id_order,0,0.0
250,fact_payment,2235,id_delivery,0,0.0
251,fact_payment,2235,id_discount,0,0.0
252,fact_payment,2235,id_site,0,0.0
253,fact_payment,2235,id_customer,0,0.0
254,fact_payment,2235,id_client,0,0.0
255,fact_payment,2235,id_payment_method,0,0.0
256,fact_payment,2235,id_location,0,0.0
257,fact_payment,2235,sk_site,0,0.0
258,fact_payment,2235,sk_discount,0,0.0
259,fact_payment,2235,sk_payment_method,0,0.0
260,fact_payment,2235,sk_customer,0,0.0
261,fact_payment,2235,sk_date_payment,0,0.0
262,fact_payment,2235,sk_date_payment_created,0,0.0
263,fact_payment,2235,sk_date_payment_modified,0,0.0
264,fact_payment,2235,sk_location,0,0.0
265,fact_payment,2235,amount,0,0.0
266,fact_payment,2235,discounted_amount,0,0.0
267,fact_payment,2235,list_of_order_items,0,0.0
268,fact_payment,2235,error,0,0.0
269,fact_payment,2235,is_error,0,0.0
270,fact_payment,2235,payment_state_id,0,0.0
271,fact_payment,2235,payment_state,0,0.0
272,fact_payment,2235,payment_type_id,0,0.0
273,fact_payment,2235,payment_type,0,0.0
274,fact_payment,2235,for_manual_handling,0,0.0
275,fact_planner_item,1931,sk_planner_item,0,0.0
276,fact_planner_item,1931,id_planner_item,0,0.0
277,fact_planner_item,1931,id_bought_offer_instance,0,0.0
278,fact_planner_item,1931,id_offer,0,0.0
279,fact_planner_item,1931,id_location,0,0.0
280,fact_planner_item,1931,id_site,0,0.0
281,fact_planner_item,1931,id_customer_address,0,0.0
282,fact_planner_item,1931,id_customer,0,0.0
283,fact_planner_item,1931,sk_start_date,0,0.0
284,fact_planner_item,1931,sk_end_date,0,0.0
285,fact_planner_item,1931,sk_customer_address,0,0.0
286,fact_planner_item,1931,sk_site,0,0.0
287,fact_planner_item,1931,sk_offer,0,0.0
288,fact_planner_item,1931,sk_location,0,0.0
289,fact_planner_item,1931,sk_customer,0,0.0
290,fact_planner_item,1931,next_version,0,0.0
291,fact_planner_item,1931,previous_version,0,0.0
292,fact_planner_item,1931,day_index,0,0.0
293,fact_planner_item,1931,sk_date_plan_created,0,0.0
294,fact_planner_item,1931,sk_date_plan_modified,0,0.0
295,fact_planner_item,1931,day_name,0,0.0
296,fact_planner_item,1931,quantity,0,0.0
297,fact_planner_item,1931,price,0,0.0
298,fact_planner_item,1931,vat,0,0.0
299,fact_planner_item,1931,gross_amount,0,0.0
300,fact_planner_item,1931,net_amount,0,0.0
301,fact_planner_item,1931,vat_amount,0,0.0
302,fact_planner_item,1931,duration_days,0,0.0
303,fact_planner_item,1931,bought_offer_instance_type_id,0,0.0
304,fact_planner_item,1931,bought_offer_instance_type,0,0.0
305,fact_planner_item,1931,planner_item_state_id,0,0.0
306,fact_planner_item,1931,planner_item_state,0,0.0
307,fact_planner_item,1931,is_active,0,0.0
308,fact_refund_item,1132,sk_refund_item,0,0.0
309,fact_refund_item,1132,id_refund_item,0,0.0
310,fact_refund_item,1132,id_refund,0,0.0
311,fact_refund_item,1132,id_product,0,0.0
312,fact_refund_item,1132,id_claim,0,0.0
313,fact_refund_item,1132,id_payment,0,0.0
314,fact_refund_item,1132,id_site,0,0.0
315,fact_refund_item,1132,id_customer,0,0.0
316,fact_refund_item,1132,id_client,0,0.0
317,fact_refund_item,1132,id_location,0,0.0
318,fact_refund_item,1132,sk_date_refund,0,0.0
319,fact_refund_item,1132,sk_date_refund_created,0,0.0
320,fact_refund_item,1132,sk_date_refund_modified,0,0.0
321,fact_refund_item,1132,sk_site,0,0.0
322,fact_refund_item,1132,sk_product,0,0.0
323,fact_refund_item,1132,sk_customer,0,0.0
324,fact_refund_item,1132,sk_location,0,0.0
325,fact_refund_item,1132,missing_product_quantity,0,0.0
326,fact_refund_item,1132,amount,0,0.0
327,fact_refund_item,1132,vat_amount,0,0.0
328,fact_refund_item,1132,refund_state,0,0.0
329,fact_refund_item,1132,refund_state_id,0,0.0
330,fact_refund_item,1132,refund_type,0,0.0
331,fact_refund_item,1132,refund_type_id,0,0.0
332,vw_map_locations,489,location_type,0,0.0
333,vw_map_locations,489,name,0,0.0
334,vw_map_locations,489,street,0,0.0
335,vw_map_locations,489,city,0,0.0
336,vw_map_locations,489,latitude,0,0.0
337,vw_map_locations,489,longitude,0,0.0
338,vw_map_locations,489,geo_point,0,0.0
339,vw_order_item_analytics,9454,id_order_item,0,0.0
340,vw_order_item_analytics,9454,id_order,0,0.0
341,vw_order_item_analytics,9454,id_bought_offer_instance,0,0.0
342,vw_order_item_analytics,9454,id_customer,0,0.0
343,vw_order_item_analytics,9454,id_offer,0,0.0
344,vw_order_item_analytics,9454,id_site,0,0.0
345,vw_order_item_analytics,9454,id_location,0,0.0
346,vw_order_item_analytics,9454,id_customer_address,0,0.0
347,vw_order_item_analytics,9454,order_date,0,0.0
348,vw_order_item_analytics,9454,order_year,0,0.0
349,vw_order_item_analytics,9454,order_quarter,0,0.0
350,vw_order_item_analytics,9454,order_month_number,0,0.0
351,vw_order_item_analytics,9454,order_month_name,0,0.0
352,vw_order_item_analytics,9454,order_weekday_number,0,0.0
353,vw_order_item_analytics,9454,order_weekday_name,0,0.0
354,vw_order_item_analytics,9454,is_order_on_weekend,0,0.0
355,vw_order_item_analytics,9454,is_order_on_holiday,0,0.0
356,vw_order_item_analytics,9454,is_order_on_working_day,0,0.0
357,vw_order_item_analytics,9454,order_created_date,0,0.0
358,vw_order_item_analytics,9454,order_modified_date,0,0.0
359,vw_order_item_analytics,9454,offer_name,0,0.0
360,vw_order_item_analytics,9454,offer_type,0,0.0
361,vw_order_item_analytics,9454,offer_state,0,0.0
362,vw_order_item_analytics,9454,products_in_offer,0,0.0
363,vw_order_item_analytics,9454,product_categories_in_offer,0,0.0
364,vw_order_item_analytics,9454,allergens_in_offer,0,0.0
365,vw_order_item_analytics,9454,customer_name,0,0.0
366,vw_order_item_analytics,9454,customer_state,0,0.0
367,vw_order_item_analytics,9454,customer_account_created_at,0,0.0
368,vw_order_item_analytics,9454,address_name,0,0.0
369,vw_order_item_analytics,9454,delivery_address,0,0.0
370,vw_order_item_analytics,9454,address_state,0,0.0
371,vw_order_item_analytics,9454,delivery_latitude,0,0.0
372,vw_order_item_analytics,9454,delivery_longitude,0,0.0
373,vw_order_item_analytics,9454,delivery_geo_point,0,0.0
374,vw_order_item_analytics,9454,dist_to_nearest_own_site_m,0,0.0
375,vw_order_item_analytics,9454,dist_to_nearest_comp_bakery_m,0,0.0
376,vw_order_item_analytics,9454,dist_to_nearest_comp_supermarket_m,0,0.0
377,vw_order_item_analytics,9454,comp_bakery_count_300m,0,0.0
378,vw_order_item_analytics,9454,comp_bakery_count_500m,0,0.0
379,vw_order_item_analytics,9454,comp_bakery_count_1000m,0,0.0
380,vw_order_item_analytics,9454,comp_bakery_count_2000m,0,0.0
381,vw_order_item_analytics,9454,comp_supermarket_count_500m,0,0.0
382,vw_order_item_analytics,9454,comp_supermarket_count_1000m,0,0.0
383,vw_order_item_analytics,9454,comp_supermarket_count_2000m,0,0.0
384,vw_order_item_analytics,9454,comp_supermarket_count_3000m,0,0.0
385,vw_order_item_analytics,9454,own_site_count_300m,0,0.0
386,vw_order_item_analytics,9454,own_site_count_500m,0,0.0
387,vw_order_item_analytics,9454,own_site_count_1000m,0,0.0
388,vw_order_item_analytics,9454,own_site_count_2000m,0,0.0
389,vw_order_item_analytics,9454,own_site_count_3000m,0,0.0
390,vw_order_item_analytics,9454,location_zone_name,0,0.0
391,vw_order_item_analytics,9454,location_zone_description,0,0.0
392,vw_order_item_analytics,9454,bakery_site_name,0,0.0
393,vw_order_item_analytics,9454,bakery_site_city,0,0.0
394,vw_order_item_analytics,9454,bakery_site_country,0,0.0
395,vw_order_item_analytics,9454,bought_offer_instance_type,0,0.0
396,vw_order_item_analytics,9454,order_item_state,0,0.0
397,vw_order_item_analytics,9454,order_state,0,0.0
398,vw_order_item_analytics,9454,is_modified_by_hand,0,0.0
399,vw_order_item_analytics,9454,quantity,0,0.0
400,vw_order_item_analytics,9454,gross_unit_price,0,0.0
401,vw_order_item_analytics,9454,vat_rate,0,0.0
402,vw_order_item_analytics,9454,gross_amount,0,0.0
403,vw_order_item_analytics,9454,net_amount,0,0.0
404,vw_order_item_analytics,9454,vat_amount,0,0.0
405,vw_planner_item_analytics,1931,id_planner_item,0,0.0
406,vw_planner_item_analytics,1931,id_bought_offer_instance,0,0.0
407,vw_planner_item_analytics,1931,id_offer,0,0.0
408,vw_planner_item_analytics,1931,id_location,0,0.0
409,vw_planner_item_analytics,1931,id_site,0,0.0
410,vw_planner_item_analytics,1931,id_customer_address,0,0.0
411,vw_planner_item_analytics,1931,id_customer,0,0.0
412,vw_planner_item_analytics,1931,subscription_start_date,0,0.0
413,vw_planner_item_analytics,1931,start_year,0,0.0
414,vw_planner_item_analytics,1931,start_quarter,0,0.0
415,vw_planner_item_analytics,1931,start_month_number,0,0.0
416,vw_planner_item_analytics,1931,start_month_name,0,0.0
417,vw_planner_item_analytics,1931,start_weekday_number,0,0.0
418,vw_planner_item_analytics,1931,start_weekday_name,0,0.0
419,vw_planner_item_analytics,1931,is_start_on_weekend,0,0.0
420,vw_planner_item_analytics,1931,is_start_on_holiday,0,0.0
421,vw_planner_item_analytics,1931,is_start_on_working_day,0,0.0
422,vw_planner_item_analytics,1931,subscription_end_date,0,0.0
423,vw_planner_item_analytics,1931,offer_name,0,0.0
424,vw_planner_item_analytics,1931,offer_type,0,0.0
425,vw_planner_item_analytics,1931,offer_state,0,0.0
426,vw_planner_item_analytics,1931,products_in_offer,0,0.0
427,vw_planner_item_analytics,1931,product_categories_in_offer,0,0.0
428,vw_planner_item_analytics,1931,allergens_in_offer,0,0.0
429,vw_planner_item_analytics,1931,customer_name,0,0.0
430,vw_planner_item_analytics,1931,customer_state,0,0.0

In [3]:
table_lineage = {
    'fact_payment': {'silver': 'stg_payment', 'bronze': 'raw_wallet_Payments'},
    'fact_order_item': {'silver': 'stg_bakery_order_items', 'bronze': 'raw_planner_BakeryOrderItems'},
    'fact_delivery_item': {'silver': 'stg_delivery_items', 'bronze': 'raw_delivery_manager_DeliveryItems'},
    'fact_refund_item': {'silver': 'stg_refund_items', 'bronze': 'raw_wallet_RefundItems'},
    'fact_planner_item': {'silver': 'stg_planner_item', 'bronze': 'raw_planner_PlannerItems'},

    'dim_customer': {'silver': 'stg_customer', 'bronze': 'raw_customer_manager_Customer'},
    'dim_customer_address': {'silver': 'stg_customer_address', 'bronze': 'raw_customer_manager_CustomerAddress'},
    'dim_product': {'silver': 'stg_bakery_product', 'bronze': 'raw_catalog_BakeryProduct'},
    'dim_payment_method': {'silver': 'stg_payment_method', 'bronze': 'raw_wallet_PaymentMethods'},
    'dim_site': {'silver': 'stg_site', 'bronze': 'raw_client_manager_Site'},
    'dim_delivery_man': {'silver': 'stg_delivery_man', 'bronze': 'raw_delivery_account_manager_DeliveryMan'},
    'dim_discount': {'silver': 'stg_discount', 'bronze': 'raw_wallet_Discounts'},
    'dim_location': {'silver': 'stg_location', 'bronze': 'raw_client_manager_Location'},
    'dim_allergen': {'silver': 'stg_allergen', 'bronze': 'raw_catalog_Allergen'},
    'dim_offer': {'silver': 'stg_bakery_offer', 'bronze': 'raw_catalog_BakeryOffer'},
    'dim_competitor': {'silver': 'stg_google_competitors', 'bronze': 'raw_google_competitors'}
}

print(f"Scanning {len(table_lineage)} main data paths. This will take a moment...")
dfs = []

for gold_table, lineage in table_lineage.items():
    silver_table = lineage['silver']
    bronze_table = lineage['bronze']

    targets = [
        ('1_Bronze', 'bronze', bronze_table),
        ('2_Silver', 'silver', silver_table),
        ('3_Gold', 'gold', gold_table)
    ]

    for layer_alias, dataset_name, table_name in targets:
        q = f"SELECT '{gold_table}' AS main_table, '{layer_alias}' AS layer, COUNT(*) AS row_count FROM `{project}.{dataset_name}.{table_name}`"

        try:
            dfs.append(client.query(q).to_dataframe())
        except Exception as e:
            print(f"Error for {dataset_name}.{table_name}: {e}")

if dfs:
    df_raw = pd.concat(dfs, ignore_index=True)
    df_pivot = df_raw.pivot(index='main_table', columns='layer', values='row_count')
    df_pivot.columns = [col.split('_')[1] for col in df_pivot.columns]

    print("\nDATA PATH CONSISTENCY AUDIT")
    display(df_pivot)
else:
    print("No data to display.")

Scanning 16 main data paths. This will take a moment...

DATA PATH CONSISTENCY AUDIT

                      Bronze  Silver  Gold
main_table
dim_allergen              15      15    16
dim_competitor           483     483   481
dim_customer             176     176   177
dim_customer_address     544     544   545
dim_delivery_man           6       6     7
dim_discount              21      21    22
dim_location              35      35    36
dim_offer                145     145   146
dim_payment_method       187     187   188
dim_product               83      83    84
dim_site                   8       8     9
fact_delivery_item      1741    1741  1741
fact_order_item         9454    9454  9454
fact_payment            2235    2235  2235
fact_planner_item       1931    1931  1931
fact_refund_item        1132    1132  1132

In [4]:
dataset = 'gold'

schema_query = f"""
    SELECT table_name, column_name
    FROM `{project}.{dataset}.INFORMATION_SCHEMA.COLUMNS`
    WHERE (table_name LIKE 'fact_%' OR table_name LIKE 'bridge_%')
      AND column_name LIKE 'id_%'
"""
schema_df = client.query(schema_query).to_dataframe()

queries = []
for table, group in schema_df.groupby('table_name'):
    cols = group['column_name'].tolist()

    orphan_counts = [f"COUNTIF(CAST(`{col}` AS STRING) = '-999999') AS `{col}`" for col in cols]

    q = f"""
    SELECT '{table}' AS table_name, COUNT(*) AS row_count,
    {', '.join(orphan_counts)}
    FROM `{project}.{dataset}.{table}`
    """
    queries.append(q)

print(f"Scanning {len(queries)} fact tables for orphaned records (-999999)...")

dfs = []
for q in queries:
    try:
        df_res = client.query(q).to_dataframe()

        df_melted = df_res.melt(id_vars=['table_name', 'row_count'], var_name='foreign_key', value_name='orphan_count')
        dfs.append(df_melted)
    except Exception as e:
        print(f"Error for table: {e}")

if dfs:
    df_orphans = pd.concat(dfs, ignore_index=True)

    df_orphans = df_orphans[df_orphans['orphan_count'] > 0].copy()

    if not df_orphans.empty:
        df_orphans['orphan_percentage'] = ((df_orphans['orphan_count'] / df_orphans['row_count']) * 100).round(2)
        df_orphans = df_orphans.sort_values(by=['orphan_percentage', 'orphan_count'], ascending=[False, False]).reset_index(drop=True)

        print(" BUSINESS EXCEPTION REPORT (Keys mapped to -999999)")
        display(df_orphans)
    else:
        print("\n Great news! The system works perfectly. No orphans (-999999) found in any fact tables.")
else:
    print("No data to scan.")

Scanning 9 fact tables for orphaned records (-999999)...
 BUSINESS EXCEPTION REPORT (Keys mapped to -999999)

,table_name,row_count,foreign_key,orphan_count,orphan_percentage
0,fact_refund_item,1132,id_claim,1131,99.91
1,fact_payment,2235,id_discount,2167,96.96
2,fact_payment,2235,id_client,1681,75.21
3,fact_refund_item,1132,id_client,844,74.56
4,fact_payment,2235,id_delivery,974,43.58
5,fact_refund_item,1132,id_location,354,31.27
6,fact_payment,2235,id_location,678,30.34
7,fact_payment,2235,id_site,403,18.03
8,fact_refund_item,1132,id_site,92,8.13
9,fact_delivery_item,1741,id_delivery_man,103,5.92
10,fact_order_item,9454,id_planner_item,392,4.15